/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include "board.h"
#include "fsl_iomuxc.h"
#include "pin_mux.h"
#include "hal_pinctrl.h"

void BOARD_InitI2C6Pins(void);
void BOARD_InitI2C3Pins(void);
/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins, assigned for the Cortex-M33 core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_TXD3__NETC_PINMUX_ETH0_TXD3, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_TXD2__NETC_PINMUX_ETH0_TXD2, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_TXD1__NETC_PINMUX_ETH0_TXD1, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_TXD0__NETC_PINMUX_ETH0_TXD0, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_TX_EN__NETC_PINMUX_ETH0_TX_EN, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_TX_ER__NETC_PINMUX_ETH0_TX_ER, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_TX_CLK__NETC_PINMUX_ETH0_TX_CLK, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_RX_DV__NETC_PINMUX_ETH0_RX_DV, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_RX_ER__NETC_PINMUX_ETH0_RX_ER, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_CRS__NETC_PINMUX_ETH0_CRS, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_COL__NETC_PINMUX_ETH0_COL, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_RX_CLK__NETC_PINMUX_ETH0_RX_CLK, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_RXD0__NETC_PINMUX_ETH0_RXD0, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_RXD1__NETC_PINMUX_ETH0_RXD1, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_RXD2__NETC_PINMUX_ETH0_RXD2, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_RXD3__NETC_PINMUX_ETH0_RXD3, 0U);

    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_TXD3__NETC_PINMUX_ETH0_TXD3, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_TXD2__NETC_PINMUX_ETH0_TXD2, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_TXD1__NETC_PINMUX_ETH0_TXD1, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_TXD0__NETC_PINMUX_ETH0_TXD0, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_TX_EN__NETC_PINMUX_ETH0_TX_EN, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_TX_ER__NETC_PINMUX_ETH0_TX_ER, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_TX_CLK__NETC_PINMUX_ETH0_TX_CLK, 0x5feU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_RX_DV__NETC_PINMUX_ETH0_RX_DV, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_RX_ER__NETC_PINMUX_ETH0_RX_ER, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_CRS__NETC_PINMUX_ETH0_CRS, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_COL__NETC_PINMUX_ETH0_COL, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_RX_CLK__NETC_PINMUX_ETH0_RX_CLK, 0x5feU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_RXD0__NETC_PINMUX_ETH0_RXD0, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_RXD1__NETC_PINMUX_ETH0_RXD1, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_RXD2__NETC_PINMUX_ETH0_RXD2, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH0_RXD3__NETC_PINMUX_ETH0_RXD3, 0x57eU);

    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH1_TXD3__NETC_PINMUX_ETH1_TXD3, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH1_TXD2__NETC_PINMUX_ETH1_TXD2, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH1_TXD1__NETC_PINMUX_ETH1_TXD1, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH1_TXD0__NETC_PINMUX_ETH1_TXD0, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH1_TX_EN__NETC_PINMUX_ETH1_TX_EN, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH1_TX_CLK__NETC_PINMUX_ETH1_TX_CLK, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH1_RX_DV__NETC_PINMUX_ETH1_RX_DV, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH1_RX_CLK__NETC_PINMUX_ETH1_RX_CLK, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH1_RXD0__NETC_PINMUX_ETH1_RXD0, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH1_RXD1__NETC_PINMUX_ETH1_RXD1, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH1_RXD2__NETC_PINMUX_ETH1_RXD2, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH1_RXD3__NETC_PINMUX_ETH1_RXD3, 0U);

    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH1_TXD3__NETC_PINMUX_ETH1_TXD3, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH1_TXD2__NETC_PINMUX_ETH1_TXD2, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH1_TXD1__NETC_PINMUX_ETH1_TXD1, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH1_TXD0__NETC_PINMUX_ETH1_TXD0, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH1_TX_EN__NETC_PINMUX_ETH1_TX_EN, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH1_TX_CLK__NETC_PINMUX_ETH1_TX_CLK, 0x5feU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH1_RX_DV__NETC_PINMUX_ETH1_RX_DV, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH1_RX_CLK__NETC_PINMUX_ETH1_RX_CLK, 0x5feU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH1_RXD0__NETC_PINMUX_ETH1_RXD0, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH1_RXD1__NETC_PINMUX_ETH1_RXD1, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH1_RXD2__NETC_PINMUX_ETH1_RXD2, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH1_RXD3__NETC_PINMUX_ETH1_RXD3, 0x57eU);

    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH2_TXD3__NETC_PINMUX_ETH2_TXD3, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH2_TXD2__NETC_PINMUX_ETH2_TXD2, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH2_TXD1__NETC_PINMUX_ETH2_TXD1, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH2_TXD0__NETC_PINMUX_ETH2_TXD0, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH2_TX_CTL__NETC_PINMUX_ETH2_TX_CTL, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH2_TX_CLK__NETC_PINMUX_ETH2_TX_CLK, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH2_RX_CTL__NETC_PINMUX_ETH2_RX_CTL, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH2_RX_CLK__NETC_PINMUX_ETH2_RX_CLK, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH2_RXD0__NETC_PINMUX_ETH2_RXD0, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH2_RXD1__NETC_PINMUX_ETH2_RXD1, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH2_RXD2__NETC_PINMUX_ETH2_RXD2, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH2_RXD3__NETC_PINMUX_ETH2_RXD3, 0U);

    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH2_TXD3__NETC_PINMUX_ETH2_TXD3, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH2_TXD2__NETC_PINMUX_ETH2_TXD2, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH2_TXD1__NETC_PINMUX_ETH2_TXD1, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH2_TXD0__NETC_PINMUX_ETH2_TXD0, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH2_TX_CTL__NETC_PINMUX_ETH2_TX_CTL, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH2_TX_CLK__NETC_PINMUX_ETH2_TX_CLK, 0x5feU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH2_RX_CTL__NETC_PINMUX_ETH2_RX_CTL, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH2_RX_CLK__NETC_PINMUX_ETH2_RX_CLK, 0x5feU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH2_RXD0__NETC_PINMUX_ETH2_RXD0, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH2_RXD1__NETC_PINMUX_ETH2_RXD1, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH2_RXD2__NETC_PINMUX_ETH2_RXD2, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH2_RXD3__NETC_PINMUX_ETH2_RXD3, 0x57eU);


    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH3_TXD3__NETC_PINMUX_ETH3_TXD3, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH3_TXD2__NETC_PINMUX_ETH3_TXD2, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH3_TXD1__NETC_PINMUX_ETH3_TXD1, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH3_TXD0__NETC_PINMUX_ETH3_TXD0, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH3_TX_CTL__NETC_PINMUX_ETH3_TX_CTL, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH3_TX_CLK__NETC_PINMUX_ETH3_TX_CLK, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH3_RX_CTL__NETC_PINMUX_ETH3_RX_CTL, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH3_RX_CLK__NETC_PINMUX_ETH3_RX_CLK, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH3_RXD0__NETC_PINMUX_ETH3_RXD0, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH3_RXD1__NETC_PINMUX_ETH3_RXD1, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH3_RXD2__NETC_PINMUX_ETH3_RXD2, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH3_RXD3__NETC_PINMUX_ETH3_RXD3, 0U);

    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH3_TXD3__NETC_PINMUX_ETH3_TXD3, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH3_TXD2__NETC_PINMUX_ETH3_TXD2, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH3_TXD1__NETC_PINMUX_ETH3_TXD1, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH3_TXD0__NETC_PINMUX_ETH3_TXD0, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH3_TX_CTL__NETC_PINMUX_ETH3_TX_CTL, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH3_TX_CLK__NETC_PINMUX_ETH3_TX_CLK, 0x5feU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH3_RX_CTL__NETC_PINMUX_ETH3_RX_CTL, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH3_RX_CLK__NETC_PINMUX_ETH3_RX_CLK, 0x5feU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH3_RXD0__NETC_PINMUX_ETH3_RXD0, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH3_RXD1__NETC_PINMUX_ETH3_RXD1, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH3_RXD2__NETC_PINMUX_ETH3_RXD2, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH3_RXD3__NETC_PINMUX_ETH3_RXD3, 0x57eU);

    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH4_MDC_GPIO1__NETC_EMDC, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH4_MDIO_GPIO2__NETC_EMDIO, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH4_TXD3__NETC_PINMUX_ETH4_TXD3, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH4_TXD2__NETC_PINMUX_ETH4_TXD2, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH4_TXD1__NETC_PINMUX_ETH4_TXD1, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH4_TXD0__NETC_PINMUX_ETH4_TXD0, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH4_TX_CTL__NETC_PINMUX_ETH4_TX_CTL, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH4_TX_CLK__NETC_PINMUX_ETH4_TX_CLK, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH4_RX_CTL__NETC_PINMUX_ETH4_RX_CTL, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH4_RX_CLK__NETC_PINMUX_ETH4_RX_CLK, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH4_RXD0__NETC_PINMUX_ETH4_RXD0, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH4_RXD1__NETC_PINMUX_ETH4_RXD1, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH4_RXD2__NETC_PINMUX_ETH4_RXD2, 0U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH4_RXD3__NETC_PINMUX_ETH4_RXD3, 0U);

    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH4_MDC_GPIO1__NETC_EMDC, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH4_MDIO_GPIO2__NETC_EMDIO, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH4_TXD3__NETC_PINMUX_ETH4_TXD3, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH4_TXD2__NETC_PINMUX_ETH4_TXD2, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH4_TXD1__NETC_PINMUX_ETH4_TXD1, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH4_TXD0__NETC_PINMUX_ETH4_TXD0, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH4_TX_CTL__NETC_PINMUX_ETH4_TX_CTL, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH4_TX_CLK__NETC_PINMUX_ETH4_TX_CLK, 0x5feU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH4_RX_CTL__NETC_PINMUX_ETH4_RX_CTL, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH4_RX_CLK__NETC_PINMUX_ETH4_RX_CLK, 0x5feU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH4_RXD0__NETC_PINMUX_ETH4_RXD0, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH4_RXD1__NETC_PINMUX_ETH4_RXD1, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH4_RXD2__NETC_PINMUX_ETH4_RXD2, 0x57eU);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_ETH4_RXD3__NETC_PINMUX_ETH4_RXD3, 0x57eU);

}

void BOARD_InitI2C6Pins(void) {                                /*!< Function assigned for the core: undefined[cm33] */
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO28__LPI2C6_SCL, 1U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO29__LPI2C6_SDA, 1U);

    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO28__LPI2C6_SCL,
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_DSE(15U) | HAL_PINCTRL_PLATFORM_IOMUXC_PAD_FSEL1(2U) |
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_OD_MASK);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO29__LPI2C6_SDA,
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_DSE(15U) | HAL_PINCTRL_PLATFORM_IOMUXC_PAD_FSEL1(2U) |
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_OD_MASK);
}

void BOARD_InitI2C3Pins(void) {                                /*!< Function assigned for the core: undefined[cm33] */
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO16__LPI2C3_SDA, 1U);
    HAL_PinctrlSetPinMux(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO17__LPI2C3_SCL, 1U);

    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO16__LPI2C3_SDA, 
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_DSE(15U) |
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_FSEL1(2U) |
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_OD_MASK);
    HAL_PinctrlSetPinCfg(HAL_PINCTRL_PLATFORM_IOMUXC_PAD_GPIO_IO17__LPI2C3_SCL, 
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_DSE(15U) |
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_FSEL1(2U) |
                        HAL_PINCTRL_PLATFORM_IOMUXC_PAD_OD_MASK);
}

void board_pins_setup(void)
{
    BOARD_InitPins();
    BOARD_InitI2C6Pins();
    BOARD_InitI2C3Pins();
}
