# Copyright 2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

CONFIG_MCUX_COMPONENT_device.startup=y
CONFIG_MCUX_COMPONENT_utility.assert=n
CONFIG_MCUX_COMPONENT_utility.debug_console_lite=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.config=y

# FreeRTOS configuration
CONFIG_MCUX_PRJSEG_middleware.freertos-kernel.generated_config=y
CONFIG_configTOTAL_HEAP_SIZE=40960
CONFIG_configTICK_RATE_HZ=1000
CONFIG_configENABLE_BACKWARD_COMPATIBILITY=n
CONFIG_configINCLUDE_FREERTOS_TASK_C_ADDITIONS_H=y
CONFIG_configRECORD_STACK_HIGH_ADDRESS=y
CONFIG_configTIMER_QUEUE_LENGTH=10
CONFIG_INCLUDE_uxTaskGetStackHighWaterMark=n
CONFIG_INCLUDE_xTaskGetIdleTaskHandle=n
CONFIG_INCLUDE_eTaskGetState=n
CONFIG_INCLUDE_xTaskAbortDelay=n
CONFIG_INCLUDE_xTaskGetHandle=n
