# The west manifest file for heterogeneous-multicore

manifest:
  defaults:
    remote: nxprealtimeedgesw

  remotes:
    - name: nxprealtimeedgesw
      url-base: https://github.com/nxp-real-time-edge-sw
    - name: nxpmcuxpresso
      url-base: https://github.com/nxp-mcuxpresso

  projects:
    - name: mcux-sdk
      remote: nxpmcuxpresso
      revision: Real-Time-Edge-v2.6-202307
    - name: FreeRTOS-Kernel
      remote: nxpmcuxpresso
      revision: Real-Time-Edge-v2.6-202307
    - name: CMSIS_5
      remote: nxpmcuxpresso
      path: mcux-sdk/CMSIS
      revision: Real-Time-Edge-v2.6-202307

  self:
    path: heterogeneous-multicore

