# The west manifest file for heterogeneous-multicore

manifest:
  defaults:
    remote: dnind

  remotes:
    - name: dnind
      url-base: ssh://git@bitbucket.sw.nxp.com/dnind

  projects:
    - name: mcux-sdk
      revision: feature/heterogeneous_multicore
    - name: FreeRTOS-Kernel
      revision: feature/aarch64_support
    - name: CMSIS_5
      path: mcux-sdk/CMSIS
      revision: feature/heterogeneous_multicore

  self:
    path: heterogeneous-multicore

