# The west manifest file for heterogeneous-multicore

manifest:
  defaults:
    remote: nxprealtimeedgesw

  remotes:
    - name: nxprealtimeedgesw
      url-base: https://github.com/nxp-real-time-edge-sw
    - name: nxpmcuxpresso
      url-base: https://github.com/nxp-mcuxpresso

  projects:
    - name: mcux-sdk
      remote: nxpmcuxpresso
      revision: Real-Time-Edge-v2.7-202312
    - name: FreeRTOS-Kernel
      remote: nxpmcuxpresso
      revision: Real-Time-Edge-v2.7-202312
    - name: CMSIS_5
      remote: nxpmcuxpresso
      path: mcux-sdk/CMSIS
      revision: Real-Time-Edge-v2.7-202312
    - name: lwip
      remote: nxpmcuxpresso
      revision: Real-Time-Edge-v2.7-202312
      path: middleware/lwip
    - name: mcux-sdk-middleware-multicore
      remote: nxpmcuxpresso
      revision: Real-Time-Edge-v2.7-202312
      path: middleware/multicore
    - name: rpmsg-lite
      remote: nxpmcuxpresso
      revision: Real-Time-Edge-v2.7-202312
      path: middleware/multicore/rpmsg_lite

  self:
    path: heterogeneous-multicore

