# The west manifest file for heterogeneous-multicore

manifest:
  defaults:
    remote: nxprealtimeedgesw

  remotes:
    - name: nxprealtimeedgesw
      url-base: https://github.com/nxp-real-time-edge-sw
    - name: nxpmcuxpresso
      url-base: https://github.com/nxp-mcuxpresso
    - name: nxpzephyr
      url-base: https://github.com/nxp-zephyr

  projects:
    - name: mcux-sdk
      remote: nxpmcuxpresso
      revision: Real-Time-Edge-v3.0-202412
    - name: FreeRTOS-Kernel
      remote: nxpmcuxpresso
      revision: Real-Time-Edge-v3.0-202412
    - name: CMSIS_5
      remote: nxpmcuxpresso
      path: mcux-sdk/CMSIS
      revision: Real-Time-Edge-v3.0-202412
    - name: lwip
      remote: nxpmcuxpresso
      revision: Real-Time-Edge-v3.0-202412
      path: middleware/lwip
    - name: mcux-sdk-middleware-multicore
      remote: nxpmcuxpresso
      revision: Real-Time-Edge-v3.0-202412
      path: middleware/multicore
    - name: rpmsg-lite
      remote: nxpmcuxpresso
      revision: Real-Time-Edge-v3.0-202412
      path: middleware/multicore/rpmsg_lite
    - name: zephyr
      remote: nxpzephyr
      revision: Real-Time-Edge-v3.0-202412
      west-commands: scripts/west-commands.yml
    - name: hal_nxp
      remote: nxpzephyr
      revision: Real-Time-Edge-v3.0-202412
      path: modules/hal/nxp
      groups:
        - hal
    - name: soem
      remote: nxprealtimeedgesw
      revision: Real-Time-Edge-v3.0-202412
      path: middleware/soem

  self:
    path: heterogeneous-multicore

