# config to select component, the format is CONFIG_USE_${component}
# Please refer to cmake files below to get available components:
#  ${SdkRootDirPath}/devices/MIMX9596/all_lib_device.cmake

set(CONFIG_USE_COMPONENT_CONFIGURATION false)

set(CONFIG_USE_common_freertos true)
set(CONFIG_USE_common_freertos_core_armv8a true)
set(CONFIG_USE_middleware_freertos-kernel_aarch64 true)
set(CONFIG_USE_middleware_freertos-kernel_extension true)
set(CONFIG_USE_middleware_freertos-kernel_heap_4 true)
set(CONFIG_USE_component_sm_clock true)
set(CONFIG_USE_component_sm_imx95_ca55 true)
set(CONFIG_USE_component_hal_clock true)
set(CONFIG_USE_component_hal_clock_imx95 true)
set(CONFIG_USE_component_sm_pinctrl true)
set(CONFIG_USE_component_hal_pinctrl true)
set(CONFIG_USE_component_hal_pinctrl_imx95 true)
set(CONFIG_USE_component_sm_power true)
set(CONFIG_USE_component_hal_power true)
set(CONFIG_USE_component_hal_power_imx95 true)
set(CONFIG_USE_component_sm_smt true)
set(CONFIG_USE_component_sm_crc true)
set(CONFIG_USE_component_sm_scmi true)
set(CONFIG_USE_device_CMSIS true)
set(CONFIG_USE_device_system_ca55 true)
set(CONFIG_USE_component_lists true)
set(CONFIG_USE_component_lpuart_adapter true)
set(CONFIG_USE_component_serial_manager_uart true)
set(CONFIG_USE_component_serial_manager true)
set(CONFIG_USE_driver_cache_armv8a true)
set(CONFIG_USE_driver_clock true)
set(CONFIG_USE_driver_common true)
set(CONFIG_USE_driver_iomuxc true)
set(CONFIG_USE_driver_mu1 true)
set(CONFIG_USE_driver_lpuart true)

set(CONFIG_USE_utilities_misc_utilities_aarch64 true)
if(${CONSOLE} STREQUAL "RAM_CONSOLE")
    set(CONFIG_USE_utility_assert_ram_console true)
    set(CONFIG_USE_utility_ram_console true)
else()
    set(CONFIG_USE_utility_assert true)
    set(CONFIG_USE_utility_debug_console true)
endif()

set(CONFIG_BOARD imx95lpd5evk19)
set(CONFIG_DEVICE_ID MIMX9596xxxxN)
set(MCUX_DEVICE "MIMX9596_ca55")
