CONFIG_MCUX_COMPONENT_device.startup=n
CONFIG_MCUX_COMPONENT_utility.ram_console=y

CONFIG_MCUX_COMPONENT_driver.irqsteer_1=n
CONFIG_MCUX_COMPONENT_driver.reset=n
CONFIG_MCUX_COMPONENT_driver.elec_spec=n
CONFIG_MCUX_COMPONENT_driver.trdc_soc=n
CONFIG_MCUX_COMPONENT_driver.supply=n
CONFIG_MCUX_COMPONENT_driver.cpu=n
CONFIG_MCUX_COMPONENT_driver.power=n
CONFIG_MCUX_COMPONENT_driver.ccm=n
CONFIG_MCUX_COMPONENT_driver.src1=n
CONFIG_MCUX_COMPONENT_driver.fro=n
